/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/commonapi/ParkDistanceControlSomeIPStubAdapter.hpp>
#include <v0/commonapi/ParkDistanceControl.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createParkDistanceControlSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< ParkDistanceControlSomeIPStubAdapter<::v0::commonapi::ParkDistanceControlStub>>(_address, _connection, _stub);
}

void initializeParkDistanceControlSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.ParkDistanceControl:v0_1:commonapi.ParkDistanceControl",
         0x1770, 0x1771, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "commonapi.ParkDistanceControl:v0_1",
        &createParkDistanceControlSomeIPStubAdapter);
}

INITIALIZER(registerParkDistanceControlSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeParkDistanceControlSomeIPStubAdapter);
}

} // namespace commonapi
} // namespace v0
