/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_COMMONAPI_PARK_DISTANCE_CONTROL_SOMEIP_STUB_ADAPTER_HPP_
#define V0_COMMONAPI_PARK_DISTANCE_CONTROL_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/commonapi/ParkDistanceControlStub.hpp>
#include <v0/commonapi/ParkDistanceControlSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename _Stub = ::v0::commonapi::ParkDistanceControlStub, typename... _Stubs>
class ParkDistanceControlSomeIPStubAdapterInternal
    : public virtual ParkDistanceControlStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< ParkDistanceControlSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> ParkDistanceControlSomeIPStubAdapterHelper;

    ~ParkDistanceControlSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        ParkDistanceControlSomeIPStubAdapterHelper::deinit();
    }

    void fireDistancesAttributeChanged(const ::v0::commonapi::ParkDistanceControl::SonarArrayStruct &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::ParkDistanceControlStub,
        CommonAPI::Version
    > getParkDistanceControlInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::ParkDistanceControlStub,
        ::v0::commonapi::ParkDistanceControl::SonarArrayStruct,
        ::v0::commonapi::ParkDistanceControl_::SonarArrayStructDeployment_t
    > getDistancesAttributeStubDispatcher;
    
    ParkDistanceControlSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        ParkDistanceControlSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< ParkDistanceControlStub>(_stub)),
        getParkDistanceControlInterfaceVersionStubDispatcher(&ParkDistanceControlStub::lockInterfaceVersionAttribute, &ParkDistanceControlStub::getInterfaceVersion, false, true),
        getDistancesAttributeStubDispatcher(
            &::v0::commonapi::ParkDistanceControlStub::lockDistancesAttribute,
            &::v0::commonapi::ParkDistanceControlStub::getDistancesAttribute,
            false,
            _stub->hasElement(0))
    {
        ParkDistanceControlSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x17d5) }, &getDistancesAttributeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>();

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x17d4)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xee48), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireDistancesAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::ParkDistanceControlStub>(_stub)->getDistancesAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void ParkDistanceControlSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireDistancesAttributeChanged(const ::v0::commonapi::ParkDistanceControl::SonarArrayStruct &_value) {
    CommonAPI::Deployable< ::v0::commonapi::ParkDistanceControl::SonarArrayStruct, ::v0::commonapi::ParkDistanceControl_::SonarArrayStructDeployment_t> deployedValue(_value, static_cast< ::v0::commonapi::ParkDistanceControl_::SonarArrayStructDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v0::commonapi::ParkDistanceControl::SonarArrayStruct,
                ::v0::commonapi::ParkDistanceControl_::SonarArrayStructDeployment_t
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xee48),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void ParkDistanceControlSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void ParkDistanceControlSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v0::commonapi::ParkDistanceControlStub, typename... _Stubs>
class ParkDistanceControlSomeIPStubAdapter
    : public ParkDistanceControlSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    ParkDistanceControlSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          ParkDistanceControlSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v0

#endif // V0_COMMONAPI_Park_Distance_Control_SOMEIP_STUB_ADAPTER_HPP_
