/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/commonapi/ParkDistanceControlSensorSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createParkDistanceControlSensorSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< ParkDistanceControlSensorSomeIPProxy>(_address, _connection);
}

void initializeParkDistanceControlSensorSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.ParkDistanceControlSensor:v0_1:commonapi.ParkDistanceControlSensor",
        0x6000, 0x101d0, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.ParkDistanceControlSensor:v0_1",
        &createParkDistanceControlSensorSomeIPProxy);
}

INITIALIZER(registerParkDistanceControlSensorSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeParkDistanceControlSensorSomeIPProxy);
}

ParkDistanceControlSensorSomeIPProxy::ParkDistanceControlSensorSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          distances_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x17d4), CommonAPI::SomeIP::event_id_t(0xee48), CommonAPI::SomeIP::method_id_t(0x17d5), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, static_cast< ::v0::commonapi::ParkDistanceControlSensor_::SonarArrayStructDeployment_t* >(nullptr))
{
}

ParkDistanceControlSensorSomeIPProxy::~ParkDistanceControlSensorSomeIPProxy() {
}

ParkDistanceControlSensorSomeIPProxy::DistancesAttribute& ParkDistanceControlSensorSomeIPProxy::getDistancesAttribute() {
    return distances_;
}


void ParkDistanceControlSensorSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> ParkDistanceControlSensorSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace commonapi
} // namespace v0
